### ISSUE TITLE
Throw when trying to get links of new object

### ISSUE THREAD

**Issue by Florian-BACHO** [vasild/cpp-ipfs-http-client#11] opened 2019-08-05 09:47 UTC
Try to get links of new object (hash: QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n) with IPFS using curl:
`curl "http://localhost:5001/api/v0/object/links?arg=QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n"`

IPFS returns:
`{"Hash":"QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n"}`

There is no "Links" field in the response.
The method Client::ObjectLinks of cpp-ipfs-api throws an exception as it tries to access to the "Links" value

**Comment by linas** [comment] 2019-10-24 17:00
Doesn't that mean that it's "working as designed"?  Returning json object with an empty Links field is not the same thing as a JSON object without a Links field.  So this doesn't seem like a bug, to me.

**Comment by vasild** [comment] 2019-10-26 10:45
Yes, that is normal - you ask for something that does not exist. I guess this happens only if the requested object does not have links, yes? And if it has links, then it works as expected?

I suspect that in some previous version, IPFS would return `"Links": []` to denote missing links, whereas now it just skips the `"Links"` property altogether. This is related: https://github.com/vasild/cpp-ipfs-api/commit/c46a0c2d40c6d4b52eac7ad5fa67af1874dfbaec

So, either close this as not a bug or mimic the old behavior and return `[]` if no links? What do you think?

**Comment by linas** [comment] 2019-10-26 16:34
I suggest "not a bug". IPFS itself is at version 0.44 and tryig to mimic an even older behavior even as it is changing seems like a poor idea.   Anyway, the object API is now considered to be "old", maybe even deprecated(?) and is replaced by the DAG API. (see one of the pull reqs)

**Closed** 2019-11-01 14:04 UTC

**Comment by linas** [comment] 2019-11-01 16:59
dag API is in pull req #20
